{{- if .Values.monstache.enabled }}
apiVersion: {{ template "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: "{{ template "bk-cmdb.fullname" . }}-monstache"
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    component: monstache
spec:
  replicas: {{ .Values.monstache.replicas }}
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
      component: monstache
  template:
    metadata:
      labels:
        {{- include "common.labels.standard" . | nindent 8 }}
        component: monstache
        values-hash: "{{ toYaml .Values | sha256sum | trunc 63 }}"
      {{- with .Values.monstache.annotations }}
      annotations:
        {{ toYaml . | indent 8 }}
      {{- end }}
      {{- if .Values.monstache.podAnnotations }}
        {{ toYaml .Values.monstache.podAnnotations | indent 8 }}
      {{- end }}
    spec:
      {{- include "cmdb.imagePullSecrets" . | nindent 6 }}
      containers:
      - name: monstache
        image: {{ .Values.image.registry }}/{{ .Values.monstache.image.repository }}:{{ .Values.monstache.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}

        workingDir: {{ .Values.monstache.workDir }}
        command: ["./monstache"]
        args: ["-f", "./etc/config.toml"]
        ports:
        - containerPort: {{ .Values.monstache.port }}
        volumeMounts:
          - name: configures
            mountPath: {{ .Values.monstache.configDir }}
          {{- include "cmdb.mongodb.certVolumeMount" . | nindent 10 }}
          {{- include "cmdb.es.certVolumeMount" . | nindent 10 }}
        {{- if .Values.monstache.resources }}
        resources: {{ toYaml .Values.monstache.resources | nindent 10 }}
        {{- end }}
      {{- with .Values.monstache.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: configures
          configMap:
            name: {{ .Release.Name }}-monstache-configures
        {{- include "cmdb.mongodb.certVolume" . | nindent 8 }}
        {{- include "cmdb.es.certVolume" . | nindent 8 }}

{{- end }}
